@echo off
setlocal enabledelayedexpansion

echo ============================================
echo   Gjallarhorn - First-time setup
echo ============================================
echo.
echo This will save your API keys to a local .env file.
echo You only need to do this once.
echo.
echo Leave a prompt blank if you don't have that key.
echo You need AT LEAST ONE of the two keys below.
echo.

set "ENV_FILE=%~dp0.env"

set "STARTGG_KEY="
set /p STARTGG_KEY="start.gg API key (https://developer.start.gg/docs/authentication): "

set "CM_KEY="
set /p CM_KEY="challengermode refresh key (leave blank if not using): "

if "!STARTGG_KEY!"=="" if "!CM_KEY!"=="" (
    echo.
    echo No keys entered. Aborting - run setup.bat again when you have at least one.
    pause
    exit /b 1
)

> "%ENV_FILE%" echo # Gjallarhorn config - generated by setup.bat
if not "!STARTGG_KEY!"=="" >> "%ENV_FILE%" echo GJALLARHORN_STARTGG=!STARTGG_KEY!
if not "!CM_KEY!"=="" >> "%ENV_FILE%" echo GJALLARHORN_CM_REFRESH_KEY=!CM_KEY!

echo.
echo Saved keys to:
echo   %ENV_FILE%
echo.
echo Setup complete. Double-click start.bat to launch Gjallarhorn.
echo.
pause
endlocal
